pimcore_feed_homepage:
    path:     /google_feed
    defaults: { _controller: PimcoreFeedBundle:Default:index }

pimcore_feed_homepage:
    path:     /facebook_feed
    defaults: { _controller: PimcoreFeedBundle:Default:index }
